### ISSUE TITLE
Exporter endpoint in readme.md missing v1/traces

### ISSUE THREAD

**Issue by mitoeth** [naikvenu/oracle-opentelemetry#1]
I think there´s an issue in the instructions. This is how it´s the exporter endpoint is written now:

exporter = OTLPSpanExporter(endpoint="https://<apm-data-upload-endpoint>.com/20200101/opentelemetry/public/",
                          headers={"authorization": "dataKey <apm-domain-data-key>"})

This didn´t work for me. I think this is how it should be written:

exporter = OTLPSpanExporter(endpoint="https://<apm-data-upload-endpoint>.com/20200101/opentelemetry/public/**v1/traces**",
                          headers={"authorization": "dataKey <apm-domain-data-key>"})

Best regards

**Comment by naikvenu** [comment]
Thanks for highlighting this Michael. I do have otel-app.py correctly mentioning this correctly but i might have missed in the doc.
The logic should actually append the v1/traces if not present. Not sure why it didnt work. I havent tested that either.
In any case, i'll add this change to readme.
